project:
  name: test-local-template
  basePackage: com.example.localtest
  pluginVersion: 0.1.15-SNAPSHOT
  createdAt: "2024-02-22T10:00:00"

architecture:
  type: onion-single
  paradigm: reactive
  framework: spring
  adaptersAsModules: false

templates:
  mode: developer
  localPath: ../backend-architecture-design-archetype-generator-templates/templates
  cache: false
