package com.pragma.test.infrastructure.config;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Main application class for test-hexagonal-granular.
 * 
 * Generated by Clean Architecture Generator.
 */
@SpringBootApplication(scanBasePackages = "com.pragma.test")
public class TestHexagonalGranularApplication {
    
    public static void main(String[] args) {
        SpringApplication.run(TestHexagonalGranularApplication.class, args);
    }
}
