package com.pragma.user.infrastructure.config;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Main application class for test-user-service.
 * 
 * Generated by Clean Architecture Generator.
 */
@SpringBootApplication(scanBasePackages = "com.pragma.user")
public class TestUserServiceApplication {
    
    public static void main(String[] args) {
        SpringApplication.run(TestUserServiceApplication.class, args);
    }
}
