project:
  name: test-remote-branch
  basePackage: com.example.remotetest
  pluginVersion: 0.1.15-SNAPSHOT
  createdAt: "2024-02-22T12:00:00"

architecture:
  type: onion-single
  paradigm: reactive
  framework: spring
  adaptersAsModules: false

templates:
  mode: production
  repository: https://github.com/somospragma/backend-architecture-design-archetype-generator-templates
  branch: invalid-branch-that-does-not-exist
  cache: true
